name: Visalian
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68822801-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8C0C8'
    - '#000000'
    - '#7090A0'
    - '#000000'
    - '#A8D0E0'
  brandStrength: 0.447368
  lightness: 0.125
  saturation: 0.556743
  rhythmicContrast: 0.648026
purpose: []
