name: Visalian
favicon: null
layout_spectrum: 0.65364
typography_spectrum: 0.45981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68822801-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A8C0C8'
    - '#000000'
    - '#7090A0'
    - '#000000'
    - '#A8D0E0'
  brandStrength: 0.9375
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
