name: Visalian
favicon: null
layout_spectrum: 0.61515
typography_spectrum: 0.20004
title: Visalian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68822801-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#0095d9'
    - '#656263'
    - '#cbcaca'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.32527831895276904
  rhythmicContrast: 0.25
purpose: []
