analytics:
  google: UA-68822801-2
color:
  brandColors:
    - '#ffffff'
    - '#f58220'
    - '#008cd2'
    - '#ed028c'
    - '#540a00'
  brandStrength: 0.625
  lightness: 0.125
  rhythmicContrast: 0.25
  saturation: 0.32527831895276904
cta: {}
layout_spectrum: 0.893092
name: Visalian
opengraph: {}
purpose: []
typography_spectrum: 0.90359
