name: Visalian
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2986602333839983
title: Visalian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68822801-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#0095d9'
    - '#656263'
    - '#cbcaca'
  brandStrength: 1
  lightness: 0.17284383391961455
  saturation: 0.32527831895276904
  rhythmicContrast: 0.9983284454792738
purpose: []
