layout_spectrum: 0.3505435805587965
typography_spectrum: 0.9542037339005066
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 0.3538611854191427
  lightness: 0.2222938869095933
  saturation: 0.1436350756118277
  rhythmicContrast: 0.6075683573717343
name: Visalian
favicon: null
title: Not so random stuff 0XCD0C28670CBC9E42
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68822801-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - type: external
    url: 'https://www.eff.org/'
    label: Please help EFF out.  More than ever.
  - type: external
    url: >-
      https://docs.google.com/spreadsheets/d/e/2PACX-1vR2KTlZnM-Xh8MVqgBtSpDi_XvCLdDCzqdh_Dj7OBcxi235_MZpQAT_lJGLV7nXD6dC5Q-4zgeL3U2U/pubchart?oid=545524534&format=interactive
    label: To the Chart!!!!
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1508071-8d48-4a5d-a6e7-ac09b1757118.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f1508071-8d48-4a5d-a6e7-ac09b1757118.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
content_rating:
  adult: false
