analytics:
  google: UA-68822801-2
color:
  brandColors:
    - '#A8C0C8'
    - '#000000'
    - '#7090A0'
    - '#000000'
    - '#A8D0E0'
  brandStrength: 0.9375
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.1875
cta: {}
layout_spectrum: 0.997532
name: Visalian
opengraph: {}
purpose: []
typography_spectrum: 0.45981
